name: Release

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:

  release-please-action:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          target-branch: main